name: Release

on:
  release:
    types: [created]

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write

    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release
